### ISSUE TITLE
[feature request] manually operation guide, dirty code optimize

### ISSUE THREAD

**Issue by kmahyyg** [Windowscoder/Inspiron-7000-power-and-fans-control#1]
Hello Sir,

Thanks for your good work.

Could you please send me a guide of manually doing those optimization instead of using ahk?

And also, please check the script you write, the hardcoded path like `C:\Users\18622\Desktop` is not a preferred way for saving files, especially for those not using official OEM system users.

**Comment by Windowscoder** [comment]
The path like “C:\Users\18622\Desktop”is just for making installer,not for controlling  the fan speed,u can change the path in the inno setup script,and make a new installer




| |
18622070636
|
|
邮箱：18622070636@163.com
|

Signature is customized by Netease Mail Master

On 09/27/2020 09:55, Patrick Young wrote:

Hello Sir,

Thanks for your good work.

Could you please send me a guide of manually doing those optimization instead of using ahk?

And also, please check the script you write, the hardcoded path like C:\Users\18622\Desktop is not a preferred way for saving files, especially for those not using official OEM system users.

**Comment by Windowscoder** [comment]
you can find the fan speed controlling mode 
in “DellFans/mode”,three exe match three fan mode.you can also use throttle stop or intel XTU to control the cpu power and voltage.the ahk script just for deploying the fan control mode and throttle stop.
| |
18622070636
|
|
邮箱：18622070636@163.com
|

Signature is customized by Netease Mail Master

On 09/27/2020 09:55, Patrick Young wrote:

Hello Sir,

Thanks for your good work.

Could you please send me a guide of manually doing those optimization instead of using ahk?

And also, please check the script you write, the hardcoded path like C:\Users\18622\Desktop is not a preferred way for saving files, especially for those not using official OEM system users.

**Comment by kmahyyg** [comment]
Okay, Thanks. I'm trying to review the AHK script to find the workflow inside it.

By the way, your phone number is leaked from Netease Mail Master. Check webpage if you care.

**Comment by Windowscoder** [comment]
thanks ,i don’t much care about my phone number.




| |
18622070636
|
|
邮箱：18622070636@163.com
|

Signature is customized by Netease Mail Master

On 09/27/2020 10:17, Patrick Young wrote:

Closed #1.
